### ISSUE TITLE
Convert/reconnect from unauthenticated chat to authenticated chat

### ISSUE THREAD

**Issue by maskati** [microsoft/omnichannel-chat-sdk#103]
Is it possible to convert an unauthenticated chat session to an authenticated chat session using the chat reconnect functionality? And do it in such a way, that the chat history of the unauthenticated session is retained and visible to the human agent in the authenticated session? So basically:
- Start an **unauthenticated** chat session
- Get the reconnect context and `reconnectId`
- Start a new **authenticated** chat session with the `reconnectId` of the **unauthenticated** session

Currently "elevating" an unauthenticated session to an authenticated session results in the agent having to deal two separate chat sessions. If this is not possible is it a limitation of the chat SDK or the Omnichannel service?

**Comment by xTEddie** [comment]
It is not a supported scenario with Omnichannel Service. Here's the list of scenarios we support: 

- Unauthenticated Chat
    - Chat Reconnect 
- Authenticated Chat
    - Chat Reconnect
    - Persistent Chat
