### ISSUE TITLE
Client Side Auto Disconnect after 3 minutes

### ISSUE THREAD

**Issue by jelly1029** [microsoft/omnichannel-chat-sdk#109]
StartChat > Endchat > StartChat > wait for a while > Agent Side Show Customer has been disconnected from the conversation.
![image](https://user-images.githubusercontent.com/12263729/156141189-a747e20f-bc19-41aa-bf00-c0c6f09ab718.png)

I try official widget don't have this issue, can i know how to solve this?

**Comment by jelly1029** [comment]
Current if endchat, if i initiate sdk i cant startchat, how i reinitiate?

**Comment by xTEddie** [comment]
Did you see any HTTP call failures in the `Network Activity`?

**Comment by xTEddie** [comment]
Root cause is the messaging client is not sending the heartbeat to keep the conversation alive on the following logic:

```
// Same instance of ChatSDK
await chatSDK.startChat(); // Sending heartbeat works fine
await chatSDK.endChat();
await chatSDK.startChat(); // Sending heartbeat stopped working
```

The fix would be to internally reset the messaging client on ending the chat instead of keeping the same messaging client instance alive.

**Comment by jelly1029** [comment]
const chatSDK = new OmnichannelChatSDK.OmnichannelChatSDK(omnichannelConfig, chatSDKConfig);
    await chatSDK.initialize();

i try this before chatSDK.startchat(), and it will not success to startchat if use this approach, can u give me sample?

**Comment by xTEddie** [comment]
@jelly1029 Their was implementation issue of the messaging client internally used in ChatSDK. We addressed it with #111. Please update the package to **latest** ([v1.0.1-main.2d305f2](https://www.npmjs.com/package/@microsoft/omnichannel-chat-sdk/v/1.0.1-main.2d305f2)) and test it.

**Comment by jelly1029** [comment]
ok thanks!

**Comment by xTEddie** [comment]
@jelly1029  Please let me know if this issue can resolved

**Comment by jelly1029** [comment]
@xTEddie yes it is resolved.
