### ISSUE TITLE
Can't resolve 'react-native'

### ISSUE THREAD

**Issue by maniskasyap** [microsoft/omnichannel-chat-sdk#137]
I am getting this error while trying to use in my application, could you please help with it?

I am using - @microsoft/omnichannel-chat-sdk@0.2.1-main.1279ae6
node version - 16.13.0

WARNING in ./node_modules/@microsoft/omnichannel-chat-sdk/lib/telemetry/AriaTelemetry.js
[0] Module not found: Error: Can't resolve 'react-native' in '/node_modules/@microsoft/omnichannel-chat-sdk/lib/telemetry'

**Comment by Matt-roki** [comment]
I have the same problem on 1.1.1

**Comment by xTEddie** [comment]
How is this package being used? This error should not be a blocker on building your application. You can take a look at our sample apps: https://github.com/microsoft/omnichannel-chat-sdk-samples

**Comment by Matt-roki** [comment]
> 

Using react-chat-widget with nextjs. Application cannot even start due to missing modules.

**Comment by xTEddie** [comment]
The root cause is due to `ReferenceError: document is not defined`. 

Next.js uses `Server-side Rendering` (SSR), meaning the HTML web page is returned from the server. `document` is a client-side object and it's not available on SSR. ChatSDK has some `document` dependencies which explains why the application failed to run. You will have to configure `Next.js` in a way to disable `SSR` on rendering the components which are depending on ChatSDK or render the component when `document` is defined.

**Comment by Matt-roki** [comment]
> 

Even with a dynamic import you still get warn react native is not installed...

`./node_modules/@microsoft/omnichannel-chat-sdk/lib/telemetry/AriaTelemetry.js
Module not found: Can't resolve 'react-native'`

**Comment by ovidb** [comment]
@Matt-roki I'm getting the same warning but I just ignoring it. Everything works in spite of that warning for us

**Comment by Matt-roki** [comment]
> @Matt-roki I'm getting the same warning but I just ignoring it. Everything works in spite of that warning for us

Yeah i know it works but I don't like warnings about packages every 2 seconds in my terminal ha

**Comment by xTEddie** [comment]
ChatSDK is supported on Web & React Native platforms. The warning is caused by ChatSDK attempting to import `react-native` package regardless of the platform to perform certain validations. The logic is being executed in a try/catch block. So, it should not be a problem even there's a warning.

**Comment by kl13nt-tng** [comment]
Can't really believe that 2 whole years later and this is still unresolved. The package is spamming our logs with these warnings even though we don't use react native and never intended on using it. There's no justification for these warnings when you can allow the code to skip the check entirely if it's not targeting react-native. Can we please get that resolved any time soon?

At least a config option to suppress these messages would be nice.
