### ISSUE TITLE
Is it possible to have multiple instances of the Chat at the same time?

### ISSUE THREAD

**Issue by ovidb** [microsoft/omnichannel-chat-sdk#145]
We have a use case where we need to have multiple chats from a single users (think Messages Center) where a user could have multiple chats with different Workstreams

We have configured two Workstreams on the Dynamics side, but when we try to connect two widgets at the same time, only the first instance of the widget works. They work by themselves if we initialize them individually. Furthermore, if we flip the instantiation, only the widget that was initialized first will work, while the other will stay in the loading state forever

For example if we switch the order of 
```
    await chatSDK2.initialize();
    await chatSDK1.initialize();
```

Then only `chatSDK2` will work, while `chatSDK1` will just stay in a loading state.

Here's a stripped down version of our code, and even you mig

```
const getConfig = (type) => {
  return {
    chat1: {
      orgId: "xxx",
      orgUrl: "xxx",
      widgetId: "xxx",
    },
    chat2: {
      orgId: "xxx1",
      orgUrl: "xxx1",
      widgetId: "xxx1",
    }
  }[type];
};


const init = async () => {
    const chatConf1 = getConfig('chat1');
    const chatConf2 = getConfig('chat2');


    const chatSDK1 = new OmnichannelChatSDK(chatConfig1, chatSDKConfig);
    const chatSDK2 = new OmnichannelChatSDK(chatConfig2, chatSDKConfig);

    await chatSDK1.initialize();
    await chatSDK2.initialize();

    const liveChatConfig1 = await chatSDK1.getLiveChatConfig();
    const liveChatConfig2 = await chatSDK2.getLiveChatConfig();

    return [
      {
        chatSDK: chatSDK1,
        chatConfig: liveChatConfig1,
        // other props
      },
      {
        chatSDK: chatSDK2,
        chatConfig: liveChatConfig2,
        // other props
      },
    ]
}

const Chats = () => {
  const chatProps = useCallback(async () => await init())
  
  if (!chatProps) return null;

  return(
    <>
      <LiveChatWidget {...chatProps[0]} />
      <LiveChatWidget {...chatProps[1]} /> 
    </>
  )
}
```

**Comment by ss-kumar** [comment]
Looks like one of the reason behind indefinite loading state is static iFrame id "Microsoft_Omnichannel_AMSClient_Iframe_Window" assigned for each instances. This can be addressed by passing multiClient flag while instantiating AMSclient as in the below code snippet but we need to update IOmnichannelConfiguration interface to pass the flag dynamically

https://github.com/microsoft/omnichannel-chat-sdk/blob/063303c5835563f66b3412fa6479aacc0fe29a08/src/OmnichannelChatSDK.ts#L206

` this.AMSClient = await createAMSClient({
                    framedMode: isBrowser(),
                    debug: false,
                    logger: undefined,
                    **multiClient: true**
                });`
Although above change fixes the indefinite loading state issue but it ends up with sharing the same conversation messages in both the instances/widgets  which needs further analysis

**Comment by ovidb** [comment]
Thank you. This seems to work now
