### ISSUE TITLE
[botframework-webchat-control] HTML rendering issue

### ISSUE THREAD

**Issue by iMicknl** [microsoft/omnichannel-chat-sdk#15]
## Describe the bug

Bot Framework Webchat is outputting the plain HTML send via Omnichannel, instead of rendering it. I am using Power Virtual Agents connected to Omnichannel.

## Version

`main`

## Browser

Edge (Chromium)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Connect a PVA bot to Omnichannel
2. Build and run `botframework-webchat-control` sample
3. See result

## Expected behavior

HTML rendered

## Screenshots
![image](https://user-images.githubusercontent.com/1424596/111795486-88355c80-88c7-11eb-9e32-c3b7e8632f9e.png)

## Additional context

This SDK is great and can be used to unblock situations where the default Omnichannel widget offers too limited styling possibilities.

**Comment by iMicknl** [comment]
It seems that Power Virtual Agents communicates via IC3 (Teams) as well when you use Omnichannel, where it uses different markup than via DirectLine.

It would be good to have a good HTML renderer in this Omnichannel chat by default, where it renders all safe HTML.

**Comment by xTEddie** [comment]
Omnichannel Chat SDK is a UX-less SDK. It's currently supported on Web & React Native. Having a custom renderer in the ChatSDK   would increase its Web dependency. We're trying to keep this SDK platform agnostic as much as possible. So, adding a HTML renderer is not part of our plan.

**Comment by iMicknl** [comment]
I am not able to test it soon, since I am not using `omnichannel-chat-sdk` in a current project, however I don't agree fully with the statement above. 😊

I encountered issues described above with `omnichannel-chat-sdk` with a simple Power Virtual Agents bot. In my opinion, this should be a scenario that is or supported by default or to be documented. I am not sure if this is just something that occurs with Power Virtual Agents, or with any Bot Framework bot.

Power Platform (PVA) + Dynamics 365 (Omnichannel for Customer Service) is a scenario we push and it doesn't make sense to have this as a non supported scenario. I can imagine that adding a custom renderer adds a lot of overhead (and I agree), but in that case it should be solved in another way.

**Comment by xTEddie** [comment]
To clarify, PVA + Omnichannel is a supported scenario. If you decided to use WebChat, we’re providing a WebChat chat adapter. However, you will add your own customization (user interface, markdown renderer, etc). You have the flexibility to pick your own markdown renderer for WebChat or even build your own. We’re just not providing a markdown renderer as part of the Chat SDK. You can even decide not to use WebChat as well and build your own chat control. We’re just providing all the necessary APIs to interact with Omnichannel and you bring your own UX since it’s a headless SDK.

**Comment by iMicknl** [comment]
Thanks @xTEddie! I understand that this is something you don't want to include in the headless SDK, however perhaps it is something that could be mentioned on the WebChat page. I understand that the webchat control is just a demo and not production ready at all, however if customer want to get started, some pointers could be helpful. See https://github.com/microsoft/omnichannel-chat-sdk/issues/17 as well, for a related conversation.

It took me quite a while to figure out and I have worked already with the BotFramework Webchat for a while.
