### ISSUE TITLE
CORS and GetParticipantsFailed

### ISSUE THREAD

**Issue by crtdaniele** [microsoft/omnichannel-chat-sdk#153]
Hi,
I tried to use the officiale sdk at version 1.1.0 in react.

I tried to configure the sdk with the params getted from ominchannel panel. When I try to launch the application, I received two errors:

Access to fetch at 'https://95346f44-e636-477a-a22c-440be21e97a8-occhannels-acs.communication.azure.com/chat/threads/19%3AJ4BrqKHinJgKPI7RwpiRS_2KMs19lgIGg6PbrQQJUT41%40thread.v2/participants?api-version=2021-09-07' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

OmnichannelChatSDK/startChat/joinConversation/error Error: GetParticipants

This is very strange because if I try to embed the default script in my react application the chat is working done.

Thanks,
Daniele

**Comment by xTEddie** [comment]
It seems to be a transient issue. Are you able to reproduce the issue consistantly?

**Comment by xTEddie** [comment]
Which API is failing specifically? What is the origin used on that failed API?

**Comment by vikvikvr** [comment]
@xTEddie the API giving CORS was `/participants?`

However, it turns out our frontend layer was adding unwanted headers to the request.

It seems to work now 👍
