### ISSUE TITLE
[botframework-webchat-control] liveChatContext is undefined on revisit

### ISSUE THREAD

**Issue by iMicknl** [microsoft/omnichannel-chat-sdk#18]
In some scenario's, `liveChatContext` in Local Storage is undefined. I am not sure why this happens, it could be that `liveChatContext` is overwritten with `undefined` when an Internal Server Error is returned by Omnichannel (which happens a lot..).

This will break the chat widget;
<img width="716" alt="Screen Shot 2021-03-21 at 21 23 46" src="https://user-images.githubusercontent.com/1424596/111919725-bc597a80-8a8b-11eb-9b06-dd5ac0cf3e2f.png">

**Possible solution:**
Make sure we only write to `liveChatContext` when it is not undefined, or remove the key from `liveChatContext`.

**Comment by skipper09** [comment]
yeah i've gotten this too. i added a check for 'undefined'
