### ISSUE TITLE
Live Chat Transcript email is not being sent

### ISSUE THREAD

**Issue by aanand07** [microsoft/omnichannel-chat-sdk#182]
I've written the below code to email chat transcript.
```
 async requestTranscript(emailAddress: string) {
    const emailTranscriptParam = {
      emailAddress,
      attachmentMessage: "Chat Transcript",
    };

    await this.#ocSDKInstance.emailLiveChatTranscript(emailTranscriptParam);
  }
  ```
In the network tab I see a successful POST request being made. But I don't receive any email. 
I've tried this multiple times, but it doesn't seem to work.

**Comment by xTEddie** [comment]
1. Is email transcript configured? 
   - Documentation can be found [here](https://learn.microsoft.com/en-us/dynamics365/customer-service/download-email-chat-transcripts)
   - There's a prerequisite to configure mailboxes before enabling email transcript feature 
2. Does email transcript work with the out-of-box chat widget?
   - If email transcript does not work with out-of-box chat widget, then it's most likely a configuration issue.
