### ISSUE TITLE
Escalation to Voice & Video - CORS Error

### ISSUE THREAD

**Issue by hyderlyger** [microsoft/omnichannel-chat-sdk#22]
"Escalation to Voice & Video" gives CORS error on initiating.

OS: Windows 10
Browser: Chrome

![cors](https://user-images.githubusercontent.com/8588772/113254965-b01dba80-92e0-11eb-8ada-a7793219cbbf.PNG)

**Comment by xTEddie** [comment]
Can you please provide your `widget snippet code`?

**Comment by hyderlyger** [comment]
Hi Edward, here it is. Would really appreciate if we can resolve this.

[video-cors-error.zip](https://github.com/microsoft/omnichannel-chat-sdk/files/6248959/video-cors-error.zip)

**Comment by xTEddie** [comment]
I see that you have a `powerappsportals` with our `Live Chat Widget` as well as a custom chat widget using `Chat SDK`. I did not see any implementation of `Escalation to Voice & Video` in the `powerappsportals` with the `Chat SDK`.

1. Did you try `Escalation to Voice & Video` with the `Chat SDK` or with the `Live Chat Widget`? 
    1. If it's not working in `Live Chat Widget`, then it's an issue on `Live Chat Widget` side and not `Chat SDK`.
1. Can you please try to host your custom chat widget outside of `powerappsportals` to test  `Escalation to Voice & Video`?
1. We have a sample app [botframework-webchat-control](https://github.com/microsoft/omnichannel-chat-sdk/tree/main/samples/botframework-webchat-control) which has `Escalation to Voice & Video` working. Does it work on your end?
1. Can you please try to build your custom chat widget and host it outside of `powerappsportals` and see if `Escalation to Voice & Video` works?

**Comment by hyderlyger** [comment]
Hey Edward, here is the source-code and a demo where you can observe that issue. FYI, Its just a demo environment.
[customchatcontrol.zip](https://github.com/microsoft/omnichannel-chat-sdk/files/6251231/customchatcontrol.zip)

**Comment by hyderlyger** [comment]
Also, can Voice & Video work on iOS and Android devices? I am aware that the OOTB chat control only supports chromium browsers and does not work on iOS (at least on my device).

**Comment by xTEddie** [comment]
> Also, can Voice & Video escalation work on iOS and Android devices (On Website)? I am aware that the OOTB chat control only supports voice&video on chromium browsers and does not work on iOS (at least this is what I observed on my device).

Unfortunately, it does not. The Chat SDK and the OOTB chat control are using the same underlying technology.

**Comment by xTEddie** [comment]
Can you please check if CORS is enabled in your portal? 

https://docs.microsoft.com/en-us/dynamics365/marketing/developer/portal-hosted#configuring-cross-origin-resource-sharing-cors

**Comment by hyderlyger** [comment]
Added site-settings for both sites CORS errors. No change
![image](https://user-images.githubusercontent.com/8588772/113551393-01de8180-960e-11eb-9fb8-5b5bf0649ea2.png)

**Comment by xTEddie** [comment]
You should only need one config with your website URL `botportalpoc.powerappsportals.com`

**Comment by hyderlyger** [comment]
> You should only need one config with your website URL `botportalpoc.powerappsportals.com`

Updated but the error is still there.
