### ISSUE TITLE
Is there a webhook which we can subscribe to for messages send to the customer?

### ISSUE THREAD

**Issue by ferodom** [microsoft/omnichannel-chat-sdk#250]
Is there a webhook which we can subscribe to for messages send to the customer? 

Use case if the mobile app is put on the background then when a new message arrives we want to send a push notification to the customer

**Comment by xTEddie** [comment]
We have `ChatSDK.onNewMessage()` to subscribe the incoming message. The mechanism used behind the scenes is a mix of long polling and Web Socket. 

https://github.com/microsoft/omnichannel-chat-sdk#on-new-message
