### ISSUE TITLE
Is there any API to switch front/back camera on mobile device?

### ISSUE THREAD

**Issue by jie-meng** [microsoft/omnichannel-chat-sdk#251]
For laptops, there is only one single API. On Android/iOS devices, there are front and back, two cameras. We I use omnichannel-chat-sdk, debug in Chrome, I find it will use a CallingBundle.js, which will check which camera to use. But there is no API for me to pass the camera selection or toggle the camera change.

I want to know how to switch the camera with omnichannel-chat-sdk within a Web application on mobile App.

![WeChatWorkScreenshot_61f4a691-bdef-4e9f-b17b-cba2310aac14](https://github.com/microsoft/omnichannel-chat-sdk/assets/7405315/db624343-cb87-47a5-a2a8-fac30ad69f19)

![WeChatWorkScreenshot_25b6ebb9-2c72-4ecb-8830-7eadbb6bc064](https://github.com/microsoft/omnichannel-chat-sdk/assets/7405315/7f68264d-78a7-443c-b9ad-0d8d7e99abb8)

**Comment by xTEddie** [comment]
Switching Front/Back Camera is currently not supported
