### ISSUE TITLE
Internal Server Error: While hitting getAgentAvailability

### ISSUE THREAD

**Issue by RahulKesharwani353** [microsoft/omnichannel-chat-sdk#253]
I am using tha latest version v1.4.7, and while calling Agent availability
![image](https://github.com/microsoft/omnichannel-chat-sdk/assets/65972077/6a8d7e0f-c133-4167-9e72-09964dcdc7fd)

there is some Internal server error
![image](https://github.com/microsoft/omnichannel-chat-sdk/assets/65972077/893376ce-ea73-480f-86e3-800d19d3c511)

even I have tried same endpoint with postman  
```
POST https://<org-url>/livechatconnector/auth/getagentavailability/<org-id>/<app-id>/<request-id>?channelId=lcw
```
The response is same

`*NOTE*` : Trying to hit by unauthenticated widget

**Comment by xTEddie** [comment]
@RahulKesharwani353 

Did you try to use the `@latest` version and see if it works? Does it reproduces still? Could you please share the `<request-id>` of the failure?
