### ISSUE TITLE
setContextProvider SDK Method doesn't work with custom chat widget (built)

### ISSUE THREAD

**Issue by lowcodelewis** [microsoft/omnichannel-chat-sdk#286]
I need to be able to use [setContextProvider](https://learn.microsoft.com/en-us/dynamics365/customer-service/developer/reference/methods/setcontextprovider) to be able to push context to the chat session being started from a custom chat widget developed using the guidance here - https://github.com/microsoft/omnichannel-chat-widget/blob/main/docs/BuildingUsingWebpack5.md (along with some extra packages and small changes here and there 😉 - https://lowcodelewis.com/blog/develop-a-custom-chat-widget-for-dynamics-365-omnichannel)

When using setContextProvider I get the following error in the console...

<img width="1423" alt="image" src="https://github.com/microsoft/omnichannel-chat-sdk/assets/103646048/df56c7fa-ea38-4af6-bc5e-e17ff7668f3d">

Is anyone able to suggest what is happening here?

Thanks in advance

Lewis Baybutt
Microsoft Business Applications MVP
lowcodelewis.com

**Comment by xTEddie** [comment]
Issue is not related to `omnichannel-chat-sdk`
