### ISSUE TITLE
How to setAuthToken on client side? 

### ISSUE THREAD

**Issue by jie-meng** [microsoft/omnichannel-chat-sdk#300]
Due to security requirements, I need to launch MSD chat with OAuth. So I followed this document [Configure authentication settings](https://learn.microsoft.com/en-us/dynamics365/customer-service/administer/create-chat-auth-settings?tabs=customerserviceadmincenter) to setup Auth on frontend and backend. I found __JavaScript client function__ need to be set in the MSD admin page. Which give an example of: auth.getAuthorizationToken.
![image](https://github.com/microsoft/omnichannel-chat-sdk/assets/7405315/0c414e55-e381-4b36-a758-59ef804f334e)

I am confused about this JavaScript client function, if I can set any function in the frontend. Why there is a dedicated [Authenticated Chat](https://github.com/microsoft/omnichannel-chat-sdk?tab=readme-ov-file#authenticated-chat) configuration in omnichannel-chat-sdk?
```javascript
const chatSDKConfig = {
    getAuthToken: async () => {
        const response = await fetch("http://contosohelp.com/token");
        if (response.ok) {
            return await response.text();
        }
        else {
            return null
        }
    }
}

const chatSDK = new OmnichannelChatSDK.OmnichannelChatSDK(omnichannelConfig, chatSDKConfig);
await chatSDK.initialize();

```

And also a [setAuthTokenProvider](https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/reference/methods/setauthtokenprovider) for chat-widget?
```javascript
window.addEventListener("lcw:ready", function handleLivechatReadyEvent(){
// Sets the auth-token provider
// Throws error if authTokenProvider is not a function
    convertToJwtToken(payloadToEncrypt).then(function (jwtToken){
        Microsoft.Omnichannel.LiveChatWidget.SDK.setAuthTokenProvider(function authTokenProvider(callback){
            callback(jwtToken);
        });
    });
});
```

So, my questions are:
1. If I use omnichannel-chat-sdk, how should I configure AuthToken?
2. If I use chat widget, how should I configure AuthToken?
3. And what should I set for __JavaScript client function__ in admin page? (If the dedicated method __getAuthToken__ for chat-sdk and __setAuthTokenProvider__ for chat-widget is used to deal with the AuthToken, there should be a fixed name method wrapped in both of the SDK. So why should we set a __JavaScript client function__ in the admin page?)

**Comment by jie-meng** [comment]
I use "@microsoft/omnichannel-chat-sdk": "^1.6.4-main.c8833e2", and setup authentication setting in admin protal.
I use
```
const chatSDKConfig = {
    getAuthToken: async () => {
        const response = await fetch("http://contosohelp.com/token");
        if (response.ok) {
            return await response.text();
        }
        else {
            return null
        }
    }
}
```
to set authToken.

But I always got 
useChatSdkStore.ts:138 
        
        
       POST https://unqc7bbd964febfee119075000d3a819-crm5.omnichannelengagementhub.com/livechatconnector/auth/sessioninit/c7bbd964-febf-ee11-9075-000d3a819692/e2a4b671-aeda-4a0d-9dde-98a72dff4f45/023d3082-4a04-4c1b-8720-b4bb1682b153?channelId=lcw 403 (Forbidden)

useChatSdkStore.ts:138 
        
        
       POST https://unqc7bbd964febfee119075000d3a819-crm5.omnichannelengagementhub.com/livechatconnector/auth/sessioninit/c7bbd964-febf-ee11-9075-000d3a819692/e2a4b671-aeda-4a0d-9dde-98a72dff4f45/023d3082-4a04-4c1b-8720-b4bb1682b153?channelId=lcw 429 (Too Many Requests)

**Comment by xTEddie** [comment]
@jie-meng 

1. You only need to pass `getAuthToken` as described here: https://github.com/microsoft/omnichannel-chat-sdk?tab=readme-ov-file#authenticated-chat
2. If chat-widget was used, `setTokenProvider()` needs to be set
3. The `JavaScript client function` is an alternative way to set the token instead of using `setTokenProvider()`
