### ISSUE TITLE
Omnichannel session getting disconnected after 3 minutes

### ISSUE THREAD

**Issue by namit008** [microsoft/omnichannel-chat-sdk#330]
After putting tab inactive for more than 3 minutes Omnichannel session getting disconnected and showing submit only.

I am using "@microsoft/omnichannel-chat-sdk": "1.4.7-main.e83f1f6" and  "botframework-webchat": "4.15.8",

![Image (3)](https://github.com/microsoft/omnichannel-chat-sdk/assets/68066146/0725c81d-9b9a-4501-b142-2b348d88cb3f)

**Comment by xTEddie** [comment]
It is by design. If the tab is inactive for a while, in this case, 3 minutes, then the service would disconnect the user from the chat.
