### ISSUE TITLE
Cached getAgentAvailability for unauthenticated conversations

### ISSUE THREAD

**Issue by alecam** [microsoft/omnichannel-chat-sdk#331]
Hello,
will it be possibile to have a non-cached version of getAgentAvailability for unauthenticated conversations?

In my scenario I would like to call it every n-seconds/minutes to check for agent availability and react to it as soon as an agent is available but it is not possible right now since it seems like the response of the getAgentAvailability is cached.

Thank you
Alessio

**Comment by xTEddie** [comment]
It is currently not supported. `getAgentAvailability` only applies for `authenticated chat` only.
