### ISSUE TITLE
Can't find "message.properties.suggestedActions"

### ISSUE THREAD

**Issue by hyderlyger** [microsoft/omnichannel-chat-sdk#43]
The latest SDK update has broke our custom chat control implementation. There seems to be no back-ward compatibility for your updates and don't you send warnings/heads-up before upgrades? 

**Main Issue:**
We are receiving these below unknown card messages on "multichoice" questions and are no longer receiving options at "(message: IRawMessage).properties.suggestedActions".

![image](https://user-images.githubusercontent.com/8588772/119333625-81e6a680-bca3-11eb-9e7a-be6731c19be4.png)

Need help.

**Comment by hyderlyger** [comment]
Browser console:
![image](https://user-images.githubusercontent.com/8588772/119339467-9f6b3e80-bcaa-11eb-8f32-d30c6bdccced.png)

**Comment by hyderlyger** [comment]
Hi, @xTEddie seems like the suggestedAnswers are now transformed into Adaptive cards but there is no guide on how to use adaptive cards. FYI, I am using this sdk without "react-native".

**Comment by xTEddie** [comment]
Hi @hyderlyger,

here's how you can validate if the message content is an adaptive card or not

```ts
import * as AdaptiveCards, { Action } from "adaptivecards";

// ...

ChatSDK.onNewMessage((message: any) => {
    const {content} = message;

    // Adaptive Cards
    if (content && content.includes('URIObject')) {
        const parser = DOMParser();
        const xmlDoc = parser.parseFromString(content, 'text/xml');

        if (xmlDoc.getElementsByTagName(HTMLConstants.tagParseError).length > 0) {
            console.warn(`[AdaptiveCard] Unable to parse XML`);
            return;
        }

        if (xmlDoc.documentElement.nodeName !== 'URIObject') {
            console.warn(`[AdaptiveCard] Wrong XML schema`);
            return;
        }

        const swiftElement = xmlDoc.getElementsByTagName('Swift')[0];
        const base64Data: any = swiftElement.getAttribute('b64');
        const data = this.b64DecodeUnicode(base64Data);

        if (!data) {
            console.warn(`[AdaptiveCard] Data is empty`);
            return;
        }

        const jsonData = JSON.parse(data);
        const { type } = jsonData;

        // Check if it's adaptive card
        if (!type.includes('message/card')) {
            return;
        }

        const adaptiveCard = new AdaptiveCards.AdaptiveCard();
        adaptiveCard.parse(jsonData);

        adaptiveCard.onExecuteAction = async (action: Action) => { // Adaptive Card event handler
            // ...
        }

        const renderedCard = adaptiveCard.render(); // Renders as HTML element
        
        // Logic to add renderedCard in the DOM     
    }
});

```

**Comment by hyderlyger** [comment]
Hi @xTEddie,

Thanks for your quick response, however, it seems like the omnichannel-chat-sdk is reverted back to sending suggestedActions and I am no longer receiving adaptive cards that I did for the last two-three days.

Can you please comment on why this is happening back and forth? and when should we expect this to change again?

Thanks

**Comment by xTEddie** [comment]
Nothing has changed on Omnichannel AFAIK. It might be a transient issue on PVA side.

**Comment by hyderlyger** [comment]
Hi @xTEddie, I am experiencing the same issue again. This is annoying as "suggestedActions" are again vanished from message object.

![image](https://user-images.githubusercontent.com/8588772/126972849-c6e8bd28-68d6-4892-8237-39594579cfc1.png)

**Comment by hyderlyger** [comment]
FYI, I was able to use your "adaptive card" code and extract suggestive actions from there.
