### ISSUE TITLE
Can't pass customContext in startChat

### ISSUE THREAD

**Issue by hyderlyger** [microsoft/omnichannel-chat-sdk#45]
Hi @xTEddie ,

**Context Issue:** Can't pass "customContext" through startChat optionalparams. Code and error screenshots are below:
  
  ![image](https://user-images.githubusercontent.com/8588772/120647833-73af3c00-c494-11eb-9f1d-63d22497afca.png)
  ![image](https://user-images.githubusercontent.com/8588772/120647980-9c373600-c494-11eb-941d-c06fc5128fed.png)
  ![image](https://user-images.githubusercontent.com/8588772/120648343-f506ce80-c494-11eb-97ff-00908969fb93.png)
  ![image](https://user-images.githubusercontent.com/8588772/120648551-3303f280-c495-11eb-9820-0940c4165d45.png)

**A Query:** I am using Omnichannels Chat with PVA Bot and want to know if the bot will receive these above "customContext variable" as "PVA context parameters" or not?

Thanks, in advance. Would really appreciate your timely response :)

**Comment by xTEddie** [comment]
@hyderlyger, You can follow the examples [here](https://github.com/microsoft/omnichannel-chat-sdk#start-chat).

It has to follow this format: 

```js
const customContext = {
    'contextKey1': {'value': 'contextValue1', 'isDisplayable': true},
    'contextKey2': {'value': 12.34, 'isDisplayable': false},
}
```

`isDisplayable` is mandatory. I will eventually add a new change to add `isDisplayable` by default if it's not set. This flag allows you to display/hide the context value in the agent's conversation summary.

**Comment by hyderlyger** [comment]
@xTEddie , thanks that fixed the issue. 

Now coming to me second question, how can I set PVA context variable from this Omnichannel-chat-context?

**Comment by hyderlyger** [comment]
@xTEddie Nevermind, just tested and it worked out of the box. Cheers!
