### ISSUE TITLE
Can't start new chat after failing to reconnect to an existing one with liveChatContext

### ISSUE THREAD

**Issue by alecam** [microsoft/omnichannel-chat-sdk#73]
Hello @xTEddie,
after failing to reconnect to a previous existing chat, I'm trying to start a new chat. But I got errors on startChat().

![image](https://user-images.githubusercontent.com/17322025/134924600-6d1c9ffb-4383-4489-a960-3e83686b099c.png)

Assuming the "context" variable is a valid liveChatContext (previously obtained) of a non valid conversation (eg. ClosedConversation), the startChat method fails. I catch the ClosedConversation error and try to start a clean chat without liveChatContext but it fails, not allowing me to start a new conversation, send messages etc...

Here are the errors I receive on the clean startChat:

![image](https://user-images.githubusercontent.com/17322025/134919906-4e2a3183-2ab4-4ac3-8928-08e59cb87b81.png)

Am I doing something wrong or is there another way to achieve what I want?

**Comment by xTEddie** [comment]
Hi @alecam ,

I recently fixed a bug on this issue. Can you please try to update @microsoft/omnichannel-chat-sdk to its latest version ([0.3.1-main.31aff70](https://www.npmjs.com/package/@microsoft/omnichannel-chat-sdk/v/0.3.1-main.31aff70))? 

It would require you to end the previous chat session to reset the internal states, then start the chat again. 

```ts
try {
  await chatSDK.startChat({liveChatContext: context});
} catch (error) {
  await chatSDK.endChat();
  await chatSDK.startChat();
}
```

**Comment by alecam** [comment]
It works like a charm, thanks a lot for your fast answer!
