### ISSUE TITLE
Split adaptive cards with Omnichannel SDK

### ISSUE THREAD

**Issue by johan-developer** [microsoft/omnichannel-chat-sdk#84]
However, unlike the normal webchat, when displaying lists of adaptive cards options these are automatically split when there are more than 5 options and the question is repeated. This behavior seems abnormal to us.
Please tell us how to get all the options displayed together.

**Comment by xTEddie** [comment]
Do you have an example?

**Comment by johan-developer** [comment]
> Do you have an example/demo?

Sure, can you see this url https://kbot-react.vercel.app/
The first card have six options. But split in two bubbles.

If you check this URL https://kbot.azurewebsites.net/ is the same bot. But this used botframework webchat not omnichannel-chat sdk.

**Comment by xTEddie** [comment]
BotFramework-WebChat is using DirectLine messaging protocol, but not in the case for Omnichannel. We're using an internal messaging platform and handles the adaptive cards differently. We're currently doing a migration to a `v2` messaging platform. 

I'd recommend to upgrade to the new messaging platform by upgrading to the latest solutions, then test the adaptive cards. (More info [here](https://docs.microsoft.com/en-us/dynamics365/customer-service/migrate-acs))

You can verify if your org is on the new or old platform from using `ChatSDK.getLiveChatConfig()`, then look for `LiveChatVersion` property.
