### ISSUE TITLE
getConversationDetails is not working anymore - returning undefined values

### ISSUE THREAD

**Issue by alecam** [microsoft/omnichannel-chat-sdk#94]
Hello,
since the 5th of December the **getConversationDetails** method is returning an object with **conversationId** and **state** _undefined_.

![image](https://user-images.githubusercontent.com/17322025/145390500-09ad9986-a77f-4b2b-a0c2-9ff393dfa8c4.png)

Sdk version is 1.0.0.

Thank you.

**Comment by xTEddie** [comment]
Is this issue still occurring?
